
server:
  port: 8080

  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true
spring:
  application:
    name: trade_site

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mialuce?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    default_batch_fetch_size: 100 #?? ???


